Add options for disabling nvme and conntrack
giantswarm/node-exporter-app pull request #136
Opened 2022-04-06 13:55 UTC by erkanerol

2022-04-06 13:58 UTC, pipo02mix commented on helm/node-exporter-app/values.yaml
> +disableNvmeCollector: false
```suggestion
disableNvmeCollector: false

```

2022-04-06 13:58 UTC, pipo02mix approved these changes
LGTM

2022-04-06 13:59 UTC, whites11 approved these changes

2022-04-06 16:28 UTC, kopiczko commented
Looks good but please make sure we have issues to restore them in our board

2022-04-07 07:04 UTC, tfussell commented
Are these both broken due to Ubuntu and working on Flatcar? If so I'd suggest mentioning reverting this setting in our CAPO Flatcar issue.

2022-04-07 07:05 UTC, tfussell requested changes
Please add a changelog entry.

2022-04-07 08:19 UTC, tfussell approved these changes

2022-04-07 08:23 UTC, erkanerol commented
@kopiczko I added an item to our dashboard. 

@tfussell This is because of the new kernel version in new ubuntu versions. Mentioned this issue here https://github.com/giantswarm/roadmap/issues/778

2022-04-07 08:33 UTC, merged